#name: Deploy Java Service
#
#on:
#  push:
#    branches: [  ] ## Desahibilite pra docker
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Tailscale
#        uses: tailscale/github-action@v2
#        with:
#          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
#
#      - name: Deploy via SSH
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.REMOTE_PORT }}
#          script: |
#            cd ~/Documentos/cda/services/clients-services
#            git pull origin develop
#            
#            # 1. Compilar el proyecto Java con Maven
#            # -DskipTests para que el deploy sea rápido
#            mvn clean package -DskipTests
#            
#            # 2. Reiniciar o Iniciar el servicio con PM2
#            # Ajustado al nombre real del archivo: services-0.0.1-SNAPSHOT.jar
#            pm2 restart clients-service || pm2 start "java -jar target/services-0.0.1-SNAPSHOT.jar" --name clients-service